-- MySQL Script generated by MySQL Workbench
-- Sat May 13 22:42:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema restaurace
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurace
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurace` DEFAULT CHARACTER SET utf8 ;
USE `restaurace` ;

-- -----------------------------------------------------
-- Table `restaurace`.`rezervace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurace`.`rezervace` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `personcount` INT NOT NULL,
  `datetime` DATETIME NOT NULL,
  `note` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `customer_email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `customer_phone_UNIQUE` (`phone` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurace`.`objednavka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurace`.`objednavka` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `price` INT NOT NULL,
  `count` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `pizza_name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurace`.`restaurace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurace`.`restaurace` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `capacity` INT NOT NULL,
  `rezervace_id` INT UNSIGNED NOT NULL,
  `objednavka_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `rezervace_id`, `objednavka_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) ,
  INDEX `fk_restaurace_reservation_idx` (`rezervace_id` ASC) ,
  INDEX `fk_restaurace_order1_idx` (`objednavka_id` ASC) ,
  CONSTRAINT `fk_restaurace_reservation`
    FOREIGN KEY (`rezervace_id`)
    REFERENCES `restaurace`.`rezervace` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_restaurace_order1`
    FOREIGN KEY (`objednavka_id`)
    REFERENCES `restaurace`.`objednavka` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
